export const patappointdata = [
  {
    doctorname: "Dr. Marvin Campbell",
    speciality: "Ophthalmology",
    apptdate: "9 Nov 2020",
    appttime: "7.00 PM",
    bookingdate: "8 Nov 2020",
    bookingtime: "10.00 AM",
    followdate: "11 Nov 2020",
    state: "Maine",
    country: "United States",
    email: "richard@example.com",
    age: 38,
    gender: "Male",
    phone: "+1 923 782 4575",
    status: "Confirm",
    amount: 75,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    doctorname: "Dr. Katharine Berthold",
    speciality: "Orthopaedics",
    apptdate: "8 Nov 2020",
    appttime: "9.00 AM",
    bookingdate: "6 Nov 2020",
    bookingtime: "8.00 AM",
    followdate: "11 Nov 2020",
    state: "Maine",
    country: "United States",
    email: "richard@example.com",
    age: 38,
    gender: "Male",
    phone: "+1 923 782 4575",
    status: "Cancelled",
    amount: 175,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    doctorname: "Dr. Linda Tobin",
    speciality: "Neurology",
    apptdate: "8 Nov 2020",
    appttime: "6.00 PM",
    bookingdate: "6 Nov 2020",
    bookingtime: "9.00 AM",
    followdate: "10 Nov 2020",
    state: "Maine",
    country: "United States",
    email: "richard@example.com",
    age: 38,
    gender: "Male",
    phone: "+1 923 782 4575",
    status: "Pending",
    amount: 450,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    doctorname: "Dr. Paul Richard",
    speciality: "Dermatology",
    apptdate: "7 Nov 2020",
    appttime: "9.00 PM",
    bookingdate: "7 Nov 2020",
    bookingtime: "11.00 AM",
    followdate: "9 Nov 2020",
    state: "Maine",
    country: "United States",
    email: "richard@example.com",
    age: 38,
    gender: "Male",
    phone: "+1 923 782 4575",
    status: "Confirm",
    amount: 275,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    doctorname: "Dr. John Gibbs",
    speciality: "Dental",
    apptdate: "6 Nov 2020",
    appttime: "8.00 PM",
    bookingdate: "4 Nov 2020",
    bookingtime: "11.00 AM",
    followdate: "8 Nov 2020",
    state: "Maine",
    country: "United States",
    email: "richard@example.com",
    age: 38,
    gender: "Male",
    phone: "+1 923 782 4575",
    status: "Completed",
    amount: 600,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    doctorname: "Dr. Olga Barlow",
    speciality: "Dental",
    apptdate: "5 Nov 2020",
    appttime: "5.00 PM",
    bookingdate: "1 Nov 2020",
    bookingtime: "7.00 AM",
    followdate: "7 Nov 2020",
    state: "Maine",
    country: "United States",
    email: "richard@example.com",
    age: 38,
    gender: "Male",
    phone: "+1 923 782 4575",
    status: "Completed",
    amount: 100,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
];
