export const upcapptData = [
  {
    patid: "#PT0016",
    patname: "Robert Wilson",
    apptdate: "11 Nov 2022",
    appttime: "10.00 AM",
    state: "New York",
    country: "United States",
    email: "richard@example.com",
    age: 38,
    gender: "Male",
    bloodg: "AB+",
    phone: "+1 923 782 4575",
    purpose: "Gemeral",
    type: "New Patient",
    paidamount: 150,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    patid: "#PT0002",
    patname: "Travis Trimble",
    apptdate: "1 Nov 2022",
    appttime: "1.00 PM",
    state: "Maine",
    country: "United States",
    email: "travistrimble@example.com",
    age: 23,
    gender: "Male",
    bloodg: "B+",
    phone: "+1 315 384 4562",
    purpose: "Gemeral",
    type: "New Patient",
    paidamount: 75,
    moneytype: "$",
    imageurl: "../../../assets/images/patient4.jpg",
  },
  {
    patid: "#PT0005",
    patname: "Gina Moore",
    apptdate: "27 Oct 2022",
    appttime: "8.00 AM",
    state: "Florida",
    country: "United States",
    email: "ginamoore@example.com",
    phone: "+1 954 820 7887",
    age: 25,
    gender: "Female",
    bloodg: "B+",
    purpose: "Gemeral",
    type: "Old Patient",
    paidamount: 250,
    moneytype: "$",
    imageurl: "../../../assets/images/patient5.jpg",
  },
];

export const todayapptData = [
  {
    patid: "#PT0006",
    patname: "Elsie Gilley",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    state: "Kentucky",
    country: "United States",
    email: "elsiegilley@example.com",
    phone: "+1 315 384 4562",
    age: 32,
    gender: "Female",
    bloodg: "O+",
    purpose: "Fever",
    type: "Old Patient",
    paidamount: 300,
    moneytype: "$",
    imageurl: "../../../assets/images/patient6.jpg",
  },
  {
    patid: "#PT0007",
    patname: "Joan Gardner",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    state: "California",
    country: "United States",
    email: "joangardner@example.com",
    phone: "+1 707 2202 603",
    age: 28,
    gender: "Male",
    bloodg: "A-",
    purpose: "General",
    type: "Old Patient",
    paidamount: 100,
    moneytype: "$",
    imageurl: "../../../assets/images/patient7.jpg",
  },
  {
    patid: "#PT0008",
    patname: "Daniel Griffing",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    state: "New Jersey",
    country: "United States",
    email: "danielgriffing@example.com",
    phone: "+1 973 773 9497",
    age: 25,
    gender: "Male",
    bloodg: "AB-",
    purpose: "General",
    type: "New Patient",
    paidamount: 75,
    moneytype: "$",
    imageurl: "../../../assets/images/patient7.jpg",
  },
  {
    patid: "#PT0009",
    patname: "Walter Roberson",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    state: "Florida",
    country: "United States",
    email: "walterrobertson@example.com",
    phone: "+1 850 358 4445",
    age: 33,
    gender: "Male",
    bloodg: "O+",
    purpose: "General",
    type: "Old Patient",
    paidamount: 350,
    moneytype: "$",
    imageurl: "../../../assets/images/patient8.jpg",
  },
  {
    patid: "#PT0010",
    patname: "Robert Rhodes",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    state: "California",
    country: "United States",
    email: "robertrhodes@example.com",
    phone: "+1 858 259 5285",
    age: 45,
    gender: "Male",
    bloodg: "B-",
    purpose: "General",
    type: "New Patient",

    paidamount: 175,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    patid: "#PT0011",
    patname: "Harry Williams",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    state: "Colorado",
    country: "United States",
    email: "harrywilliams@example.com",
    phone: "+1 303 607 7075",
    age: 27,
    gender: "Male",
    bloodg: "O+",
    purpose: "General",
    type: "New Patient",
    paidamount: 450,
    moneytype: "$",
    imageurl: "../../../assets/images/patient4.jpg",
  },
];
