export const allapptData = [
  {
    patid: "#PT0016",
    patname: "Robert Wilson",
    apptdate: "11 Nov 2019",
    appttime: "10.00 AM",
    purpose: "Gemeral",
    type: "New Patient",
    paidamount: 150,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    patid: "#PT0002",
    patname: "Travis Trimble",
    apptdate: "1 Nov 2019",
    appttime: "1.00 PM",
    purpose: "Gemeral",
    type: "New Patient",
    paidamount: 75,
    moneytype: "$",
    imageurl: "../../../assets/images/patient4.jpg",
  },
  {
    patid: "#PT0005",
    patname: "Gina Moore",
    apptdate: "27 Oct 2019",
    appttime: "8.00 AM",
    purpose: "Gemeral",
    type: "Old Patient",
    paidamount: 250,
    moneytype: "$",
    imageurl: "../../../assets/images/patient5.jpg",
  },
];

export const todayapptData = [
  {
    patid: "#PT0006",
    patname: "Elsie Gilley",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    purpose: "Fever",
    type: "Old Patient",
    paidamount: 300,
    moneytype: "$",
    imageurl: "../../../assets/images/patient6.jpg",
  },
  {
    patid: "#PT0006",
    patname: "Joan Gardner",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    purpose: "General",
    type: "Old Patient",
    paidamount: 100,
    moneytype: "$",
    imageurl: "../../../assets/images/patient7.jpg",
  },
  {
    patid: "#PT0007",
    patname: "Daniel Griffing",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    purpose: "General",
    type: "New Patient",
    paidamount: 75,
    moneytype: "$",
    imageurl: "../../../assets/images/patient7.jpg",
  },
  {
    patid: "#PT0008",
    patname: "Walter Roberson",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    purpose: "General",
    type: "Old Patient",
    paidamount: 350,
    moneytype: "$",
    imageurl: "../../../assets/images/patient8.jpg",
  },
  {
    patid: "#PT0010",
    patname: "Robert Rhodes",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    purpose: "General",
    type: "New Patient",
    paidamount: 175,
    moneytype: "$",
    imageurl: "../../../assets/images/patient3.jpg",
  },
  {
    patid: "#PT0011",
    patname: "Harry Williams",
    apptdate: "14 Feb 2022",
    appttime: "6.00 PM",
    purpose: "General",
    type: "New Patient",
    paidamount: 450,
    moneytype: "$",
    imageurl: "../../../assets/images/patient4.jpg",
  },
];
