export const slotdata = [
    {
      patid: "#PT0016",
      patname: "Robert Wilson",
      apptdate: "11 Nov 2022",
      appttime: "10.00 AM",
      state: "New York",
      country: "United States",
      email: "richard@example.com",
      age: 38,
      gender: "Male",
      bloodg: "AB+",
      phone: "+1 923 782 4575",
      purpose: "Gemeral",
      type: "New Patient",
      paidamount: 150,
      moneytype: "$",
      imageurl: "../../../assets/images/patient3.jpg",
    },
    {
      patid: "#PT0002",
      patname: "Travis Trimble",
      apptdate: "1 Nov 2022",
      appttime: "1.00 PM",
      state: "Maine",
      country: "United States",
      email: "travistrimble@example.com",
      age: 23,
      gender: "Male",
      bloodg: "B+",
      phone: "+1 315 384 4562",
      purpose: "Gemeral",
      type: "New Patient",
      paidamount: 75,
      moneytype: "$",
      imageurl: "../../../assets/images/patient4.jpg",
    },
    {
      patid: "#PT0005",
      patname: "Gina Moore",
      apptdate: "27 Oct 2022",
      appttime: "8.00 AM",
      state: "Florida",
      country: "United States",
      email: "ginamoore@example.com",
      phone: "+1 954 820 7887",
      age: 25,
      gender: "Female",
      bloodg: "B+",
      purpose: "Gemeral",
      type: "Old Patient",
      paidamount: 250,
      moneytype: "$",
      imageurl: "../../../assets/images/patient5.jpg",
    },
  ];